# version: '3.9'

# services:
#   mongodb:
#     image: mongo:5.0
#     ports:
#       - 27017:27017
#     environment:
#       - MONGO_INITDB_ROOT_USERNAME=manuel101284
#       - MONGO_INITDB_ROOT_PASSWORD=castellanos
#     volumes:
#       - ./mongo_data:/data/db
